[Issue-112] Upgrade pravega client version to 0.9.1
pravega/spark-connectors pull request #115
Opened 2021-04-20 08:43 UTC by thekingofcity

Signed-off-by: zhongle.wang <zhongle_wang@dell.com>

**Change log description**

Upgrade pravega version to the latest commit pravega/pravega@26b543c

**Purpose of the change**

Fix #112 

**What the code does**

Upgrade pravega version to the latest commit pravega/pravega@26b543c

**How to verify it**

`./gradlew build` passes

2021-04-20 14:40 UTC, claudiofahey requested changes
Why are we upgrading to 0.9.1-SNAPSHOT? I would suggest upgrading to pravegaVersion 0.9.0 (non-snapshot).

2021-04-21 02:48 UTC, claudiofahey commented
Let's change the target branch to `r0.9-spark3.0` so that the naming convention is consistent with the other branches.

2021-04-21 02:56 UTC, crazyzhou approved these changes
LGTM

2021-04-21 02:56 UTC, claudiofahey approved these changes

2021-04-21 02:58 UTC, merged